### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by TheDataLeek** [jart/fabulous#11]
When installing with pip3 this fails because of the py2-style print commands. All of the documentation also uses py2 syntax.

What is the roadmap for python 3 support?

**Comment by jart** [comment]
You're the first person to request it. If you want it, I'll do it.

**Comment by TheDataLeek** [comment]
Yeah, that would be awesome! I mostly just use Python 3, and it would be cool to start incorporating this into some of my tools. Colours always make things better and using the raw ANSI codes is a huge pain.

Cheers!

**Comment by willtheorangeguy** [comment]
It would love it too if you could do Python 3 because I mostly use it too.

**Comment by jart** [comment]
Ok working on it.

**Comment by willtheorangeguy** [comment]
I'd be fine with helping if you need it.

**Comment by jart** [comment]
I'm going to need though code review. I'll send out a pull request to all
of you today or tomorrow. Once it's submitted I'll cut a new release.

**Comment by jart** [comment]
Correction: thorough

**Comment by willtheorangeguy** [comment]
OK

**Comment by TheDataLeek** [comment]
Sounds good! I don't have a ton of time to contribute to the project, but I'd be more than happy to help review.

Thanks!

**Comment by jart** [comment]
Is it considered acceptable to not support 3.0, 3.1, and 3.2? As in, 3 support would only be 3.3 and greater.

**Comment by jart** [comment]
Yeah Python 2∩3 is not a fun language. Almost done.

**Comment by jart** [comment]
For posterity: https://github.com/jart/fabulous/pull/12

**Comment by jart** [comment]
@arielb2 @willzfarmer @willtheorangeguy I just cut a Python 3.{3,4,5} compatible release. Enjoy!
- https://github.com/jart/fabulous/releases/tag/0.3.0
- https://pypi.python.org/pypi/fabulous/0.3.0

**Comment by willtheorangeguy** [comment]
Thanks for working on that!!
