### ISSUE TITLE
Nitpick:  please specify the license of the fonts files.

### ISSUE THREAD

**Issue by laarmen** [jart/fabulous#2]
Hi,

I'm packaging this module for Debian as part of a chain of dependencies for fedmsg, and sadly I had to repack the tarball as there was no license information for the fonts/ directory. Would it be possible to fix this?

There's no hurry though, as I'm going to use the system fonts anyway.

**Comment by jart** [comment]
Thanks for bringing this concern. I've updated Fabulous to bundle Google Noto Fonts, which are very kosher from a licensing perspective. See https://github.com/jart/fabulous/tree/master/fabulous/fonts
