### ISSUE TITLE
Does not work from local directory

### ISSUE THREAD

**Issue by Tcll** [jart/fabulous#6]
1: download repo as zip
2: create test.py in repo directory
3: code for test.py:

```
from fabulous import text
print text.Text("Fabulous", color='#0099ff', shadow=True, scew=5)
```

error when D-clicking test.py:

```
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "\home\tcll\Desktop\fabulous-master\test.py", line 1, in <module>
    from fabulous import text
  File "\home\tcll\Desktop\fabulous-master\fabulous\text.py", line 46, in <module>
    import grapefruit
ImportError: No module named grapefruit
>>> 
```

if this module needs to be compiled, please distribute binary builds with the src.
normal users just want to download and run, not compile.

**Comment by stuaxo** [comment]
You need to install grapefruit first  https://pypi.python.org/pypi/grapefruit/0.1a3

**Comment by jart** [comment]
Grapefruit is bundled with Fabulous as of [v0.1.7](https://github.com/jart/fabulous/releases/tag/0.1.7) so I'm marking this issue obsolete. Thank you for taking the time to report it @Tcll!

You might also be interested in knowing that a lot of work has been done maintaining Fabulous the past few weeks. We're now up to v0.3.0. No breaking API changes have really happened. I mostly just brought the library into a really healthy state. Check out the [release notes](https://github.com/jart/fabulous/releases).

**Comment by Tcll** [comment]
sorry for not responding soon, don't wanna be a douche. ;)
thanks for the update :)
I will try this out
