### ISSUE TITLE
Named source 0.1.8.tar.gz

### ISSUE THREAD

**Issue by arielb2** [jart/fabulous#8]
can you use the previous standard in the name please?
fabulous-0.1.8.tar.gz instance of 0.1.8.tar.gz

**Comment by jart** [comment]
There are named source dists uploaded to pypi: https://pypi.python.org/simple/fabulous/ But they don't contain the full set of sources. It's the thing that `python setup.py sdist` generates. It only contain the things actually needed when installing via pip. Like fonts and an egg-info dir. It excludes files like docs, tests, etc.

Is this considered a best practice? Or should I tweak my MANIFEST.in to contain everything?

Nevertheless, I've updated the release page to contain named tarballs with the full GitHub sources: https://github.com/jart/fabulous/releases

Thank you for packaging this on Fedora!

**Comment by jart** [comment]
Assuming you're a Fedora packager, I've updated the [python-fabulous.spec](https://github.com/jart/fabulous/blob/master/python-fabulous.spec) file with the latest knowledge.
